export const NATIONALITIES = [
  { value: "Afghan", label: "Afghan", code: "af" },
  { value: "Albanian", label: "Albanian", code: "al" },
  { value: "Algerian", label: "Algerian", code: "dz" },
  { value: "American", label: "American", code: "um" },
  { value: "American Samoan", label: "American Samoan", code: "as" },
  { value: "Andorran", label: "Andorran", code: "ad" },
  { value: "Angolan", label: "Angolan", code: "ao" },
  { value: "Anguillan", label: "Anguillan", code: "ai" },
  { value: "Antarctic", label: "Antarctic", code: "aq" },
  { value: "Antiguan or Barbudan", label: "Antiguan or Barbudan", code: "ag" },
  { value: "Argentine", label: "Argentine", code: "ar" },
  { value: "Armenian", label: "Armenian", code: "am" },
  { value: "Aruban", label: "Aruban", code: "aw" },
  { value: "Australian", label: "Australian", code: "au" },
  { value: "Austrian", label: "Austrian", code: "at" },
  { value: "Azerbaijani, Azeri", label: "Azerbaijani, Azeri", code: "az" },
  { value: "BIOT", label: "BIOT", code: "io" },
  { value: "Bahamian", label: "Bahamian", code: "bs" },
  { value: "Bahraini", label: "Bahraini", code: "bh" },
  { value: "Bangladeshi", label: "Bangladeshi", code: "bd" },
  { value: "Barbadian", label: "Barbadian", code: "bb" },
  { value: "Barthélemois", label: "Barthélemois", code: "bl" },
  { value: "Basotho", label: "Basotho", code: "ls" },
  { value: "Belarusian", label: "Belarusian", code: "by" },
  { value: "Belgian", label: "Belgian", code: "be" },
  { value: "Belizean", label: "Belizean", code: "bz" },
  { value: "Beninese, Beninois", label: "Beninese, Beninois", code: "bj" },
  { value: "Bermudian, Bermudan", label: "Bermudian, Bermudan", code: "bm" },
  { value: "Bhutanese", label: "Bhutanese", code: "bt" },
  { value: "Bissau-Guinean", label: "Bissau-Guinean", code: "gw" },
  { value: "Bolivian", label: "Bolivian", code: "bo" },
  { value: "Bonaire", label: "Bonaire", code: "bq" },
  { value: "Bosnian or Herzegovinian", label: "Bosnian or Herzegovinian", code: "ba" },
  { value: "Bouvet Island", label: "Bouvet Island", code: "bv" },
  { value: "Brazilian", label: "Brazilian", code: "br" },
  { value: "British Virgin Island", label: "British Virgin Island", code: "vg" },
  { value: "British, UK", label: "British, UK", code: "gb" },
  { value: "Bruneian", label: "Bruneian", code: "bn" },
  { value: "Bulgarian", label: "Bulgarian", code: "bg" },
  { value: "Burkinabé", label: "Burkinabé", code: "bf" },
  { value: "Burmese", label: "Burmese", code: "mm" },
  { value: "Burundian", label: "Burundian", code: "bi" },
  { value: "Cabo Verdean", label: "Cabo Verdean", code: "cv" },
  { value: "Cambodian", label: "Cambodian", code: "kh" },
  { value: "Cameroonian", label: "Cameroonian", code: "cm" },
  { value: "Canadian", label: "Canadian", code: "ca" },
  { value: "Caymanian", label: "Caymanian", code: "ky" },
  { value: "Central African", label: "Central African", code: "cf" },
  { value: "Chadian", label: "Chadian", code: "td" },
  { value: "Channel Island", label: "Channel Island", code: "gg" },
  { value: "Chilean", label: "Chilean", code: "cl" },
  { value: "Chinese", label: "Chinese", code: "cn" },
  { value: "Chinese, Taiwanese", label: "Chinese, Taiwanese", code: "tw" },
  { value: "Christmas Island", label: "Christmas Island", code: "cx" },
  { value: "Cocos Island", label: "Cocos Island", code: "cc" },
  { value: "Colombian", label: "Colombian", code: "co" },
  { value: "Comoran, Comorian", label: "Comoran, Comorian", code: "km" },
  { value: "Congolese", label: "Congolese", code: "cg" },
  { value: "Cook Island", label: "Cook Island", code: "ck" },
  { value: "Costa Rican", label: "Costa Rican", code: "cr" },
  { value: "Croatian", label: "Croatian", code: "hr" },
  { value: "Cuban", label: "Cuban", code: "cu" },
  { value: "Curaçaoan", label: "Curaçaoan", code: "cw" },
  { value: "Cypriot", label: "Cypriot", code: "cy" },
  { value: "Czech", label: "Czech", code: "cz" },
  { value: "Danish", label: "Danish", code: "dk" },
  { value: "Djiboutian", label: "Djiboutian", code: "dj" },
  { value: "Dominican", label: "Dominican", code: "dm" },
  { value: "Dutch, Netherlandic", label: "Dutch, Netherlandic", code: "nl" },
  { value: "Ecuadorian", label: "Ecuadorian", code: "ec" },
  { value: "Egyptian", label: "Egyptian", code: "eg" },
  { value: "Emirati, Emirian, Emiri", label: "Emirati, Emirian, Emiri", code: "ae" },
  { value: "Equatorial Guinean, Equatoguinean", label: "Equatorial Guinean, Equatoguinean", code: "gq" },
  { value: "Eritrean", label: "Eritrean", code: "er" },
  { value: "Estonian", label: "Estonian", code: "ee" },
  { value: "Ethiopian", label: "Ethiopian", code: "et" },
  { value: "Falkland Island", label: "Falkland Island", code: "fk" },
  { value: "Faroese", label: "Faroese", code: "fo" },
  { value: "Fijian", label: "Fijian", code: "fj" },
  { value: "Finnish", label: "Finnish", code: "fi" },
  { value: "French", label: "French", code: "fr" },
  { value: "French Guianese", label: "French Guianese", code: "gf" },
  { value: "French Polynesian", label: "French Polynesian", code: "pf" },
  { value: "French Southern Territories", label: "French Southern Territories", code: "tf" },
  { value: "Gabonese", label: "Gabonese", code: "ga" },
  { value: "Gambian", label: "Gambian", code: "gm" },
  { value: "Georgian", label: "Georgian", code: "ge" },
  { value: "German", label: "German", code: "de" },
  { value: "Ghanaian", label: "Ghanaian", code: "gh" },
  { value: "Gibraltar", label: "Gibraltar", code: "gi" },
  { value: "Greek, Hellenic", label: "Greek, Hellenic", code: "gr" },
  { value: "Greenlandic", label: "Greenlandic", code: "gl" },
  { value: "Grenadian", label: "Grenadian", code: "gd" },
  { value: "Guadeloupe", label: "Guadeloupe", code: "gp" },
  { value: "Guamanian, Guambat", label: "Guamanian, Guambat", code: "gu" },
  { value: "Guatemalan", label: "Guatemalan", code: "gt" },
  { value: "Guinean", label: "Guinean", code: "gn" },
  { value: "Guyanese", label: "Guyanese", code: "gy" },
  { value: "Haitian", label: "Haitian", code: "ht" },
  { value: "Heard Island or McDonald Islands", label: "Heard Island or McDonald Islands", code: "hm" },
  { value: "Honduran", label: "Honduran", code: "hn" },
  { value: "Hong Kong, Hong Kongese", label: "Hong Kong, Hong Kongese", code: "hk" },
  { value: "Hungarian, Magyar", label: "Hungarian, Magyar", code: "hu" },
  { value: "I-Kiribati", label: "I-Kiribati", code: "ki" },
  { value: "Icelandic", label: "Icelandic", code: "is" },
  { value: "Indian", label: "Indian", code: "in" },
  { value: "Indonesian", label: "Indonesian", code: "id" },
  { value: "Iranian, Persian", label: "Iranian, Persian", code: "ir" },
  { value: "Iraqi", label: "Iraqi", code: "iq" },
  { value: "Irish", label: "Irish", code: "ie" },
  { value: "Israeli", label: "Israeli", code: "il" },
  { value: "Italian", label: "Italian", code: "it" },
  { value: "Ivorian", label: "Ivorian", code: "ci" },
  { value: "Jamaican", label: "Jamaican", code: "jm" },
  { value: "Japanese", label: "Japanese", code: "jp" },
  { value: "Jordanian", label: "Jordanian", code: "jo" },
  { value: "Kazakhstani, Kazakh", label: "Kazakhstani, Kazakh", code: "kz" },
  { value: "Kenyan", label: "Kenyan", code: "ke" },
  { value: "Kittitian or Nevisian", label: "Kittitian or Nevisian", code: "kn" },
  { value: "Kuwaiti", label: "Kuwaiti", code: "kw" },
  { value: "Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz", label: "Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz", code: "kg" },
  { value: "Lao, Laotian", label: "Lao, Laotian", code: "la" },
  { value: "Latvian", label: "Latvian", code: "lv" },
  { value: "Lebanese", label: "Lebanese", code: "lb" },
  { value: "Liberian", label: "Liberian", code: "lr" },
  { value: "Libyan", label: "Libyan", code: "ly" },
  { value: "Liechtenstein", label: "Liechtenstein", code: "li" },
  { value: "Lithuanian", label: "Lithuanian", code: "lt" },
  { value: "Luxembourg, Luxembourgish", label: "Luxembourg, Luxembourgish", code: "lu" },
  { value: "Macanese, Chinese", label: "Macanese, Chinese", code: "mo" },
  { value: "Macedonian", label: "Macedonian", code: "mk" },
  { value: "Mahoran", label: "Mahoran", code: "yt" },
  { value: "Malagasy", label: "Malagasy", code: "mg" },
  { value: "Malawian", label: "Malawian", code: "mw" },
  { value: "Malaysian", label: "Malaysian", code: "my" },
  { value: "Maldivian", label: "Maldivian", code: "mv" },
  { value: "Malian, Malinese", label: "Malian, Malinese", code: "ml" },
  { value: "Maltese", label: "Maltese", code: "mt" },
  { value: "Manx", label: "Manx", code: "im" },
  { value: "Marshallese", label: "Marshallese", code: "mh" },
  { value: "Martiniquais, Martinican", label: "Martiniquais, Martinican", code: "mq" },
  { value: "Mauritanian", label: "Mauritanian", code: "mr" },
  { value: "Mauritian", label: "Mauritian", code: "mu" },
  { value: "Mexican", label: "Mexican", code: "mx" },
  { value: "Micronesian", label: "Micronesian", code: "fm" },
  { value: "Moldovan", label: "Moldovan", code: "md" },
  { value: "Mongolian", label: "Mongolian", code: "mn" },
  { value: "Montenegrin", label: "Montenegrin", code: "me" },
  { value: "Montserratian", label: "Montserratian", code: "ms" },
  { value: "Monégasque, Monacan", label: "Monégasque, Monacan", code: "mc" },
  { value: "Moroccan", label: "Moroccan", code: "ma" },
  { value: "Motswana, Botswanan", label: "Motswana, Botswanan", code: "bw" },
  { value: "Mozambican", label: "Mozambican", code: "mz" },
  { value: "Namibian", label: "Namibian", code: "na" },
  { value: "Nauruan", label: "Nauruan", code: "nr" },
  { value: "Nepali, Nepalese", label: "Nepali, Nepalese", code: "np" },
  { value: "New Caledonian", label: "New Caledonian", code: "nc" },
  { value: "New Zealand, NZ", label: "New Zealand, NZ", code: "nz" },
  { value: "Ni-Vanuatu, Vanuatuan", label: "Ni-Vanuatu, Vanuatuan", code: "vu" },
  { value: "Nicaraguan", label: "Nicaraguan", code: "ni" },
  { value: "Nigerian", label: "Nigerian", code: "ng" },
  { value: "Nigerien", label: "Nigerien", code: "ne" },
  { value: "Niuean", label: "Niuean", code: "nu" },
  { value: "Norfolk Island", label: "Norfolk Island", code: "nf" },
  { value: "North Korean", label: "North Korean", code: "kp" },
  { value: "Northern Marianan", label: "Northern Marianan", code: "mp" },
  { value: "Norwegian", label: "Norwegian", code: "no" },
  { value: "Omani", label: "Omani", code: "om" },
  { value: "Pakistani", label: "Pakistani", code: "pk" },
  { value: "Palauan", label: "Palauan", code: "pw" },
  { value: "Palestinian", label: "Palestinian", code: "ps" },
  { value: "Panamanian", label: "Panamanian", code: "pa" },
  { value: "Papua New Guinean, Papuan", label: "Papua New Guinean, Papuan", code: "pg" },
  { value: "Paraguayan", label: "Paraguayan", code: "py" },
  { value: "Peruvian", label: "Peruvian", code: "pe" },
  { value: "Philippine, Filipino", label: "Philippine, Filipino", code: "ph" },
  { value: "Pitcairn Island", label: "Pitcairn Island", code: "pn" },
  { value: "Polish", label: "Polish", code: "pl" },
  { value: "Portuguese", label: "Portuguese", code: "pt" },
  { value: "Puerto Rican", label: "Puerto Rican", code: "pr" },
  { value: "Qatari", label: "Qatari", code: "qa" },
  { value: "Romanian", label: "Romanian", code: "ro" },
  { value: "Russian", label: "Russian", code: "ru" },
  { value: "Rwandan", label: "Rwandan", code: "rw" },
  { value: "Réunionese, Réunionnais", label: "Réunionese, Réunionnais", code: "re" },
  { value: "Sahrawi, Sahrawian, Sahraouian", label: "Sahrawi, Sahrawian, Sahraouian", code: "eh" },
  { value: "Saint Helenian", label: "Saint Helenian", code: "sh" },
  { value: "Saint Lucian", label: "Saint Lucian", code: "lc" },
  { value: "Saint Vincentian, Vincentian", label: "Saint Vincentian, Vincentian", code: "vc" },
  { value: "Saint-Martinoise", label: "Saint-Martinoise", code: "mf" },
  { value: "Saint-Pierrais or Miquelonnais", label: "Saint-Pierrais or Miquelonnais", code: "pm" },
  { value: "Salvadoran", label: "Salvadoran", code: "sv" },
  { value: "Sammarinese", label: "Sammarinese", code: "sm" },
  { value: "Samoan", label: "Samoan", code: "ws" },
  { value: "Saudi, Saudi Arabian", label: "Saudi, Saudi Arabian", code: "sa" },
  { value: "Senegalese", label: "Senegalese", code: "sn" },
  { value: "Serbian", label: "Serbian", code: "rs" },
  { value: "Seychellois", label: "Seychellois", code: "sc" },
  { value: "Sierra Leonean", label: "Sierra Leonean", code: "sl" },
  { value: "Singaporean", label: "Singaporean", code: "sg" },
  { value: "Sint Maarten", label: "Sint Maarten", code: "sx" },
  { value: "Slovak", label: "Slovak", code: "sk" },
  { value: "Slovenian, Slovene", label: "Slovenian, Slovene", code: "si" },
  { value: "Solomon Island", label: "Solomon Island", code: "sb" },
  { value: "Somali, Somalian", label: "Somali, Somalian", code: "so" },
  { value: "South African", label: "South African", code: "za" },
  { value: "South Georgia or South Sandwich Islands", label: "South Georgia or South Sandwich Islands", code: "gs" },
  { value: "South Korean", label: "South Korean", code: "kr" },
  { value: "South Sudanese", label: "South Sudanese", code: "ss" },
  { value: "Spanish", label: "Spanish", code: "es" },
  { value: "Sri Lankan", label: "Sri Lankan", code: "lk" },
  { value: "Sudanese", label: "Sudanese", code: "sd" },
  { value: "Surinamese", label: "Surinamese", code: "sr" },
  { value: "Svalbard", label: "Svalbard", code: "sj" },
  { value: "Swazi", label: "Swazi", code: "sz" },
  { value: "Swedish", label: "Swedish", code: "se" },
  { value: "Swiss", label: "Swiss", code: "ch" },
  { value: "Syrian", label: "Syrian", code: "sy" },
  { value: "São Toméan", label: "São Toméan", code: "st" },
  { value: "Tajikistani", label: "Tajikistani", code: "tj" },
  { value: "Tanzanian", label: "Tanzanian", code: "tz" },
  { value: "Thai", label: "Thai", code: "th" },
  { value: "Timorese", label: "Timorese", code: "tl" },
  { value: "Togolese", label: "Togolese", code: "tg" },
  { value: "Tokelauan", label: "Tokelauan", code: "tk" },
  { value: "Tongan", label: "Tongan", code: "to" },
  { value: "Trinidadian or Tobagonian", label: "Trinidadian or Tobagonian", code: "tt" },
  { value: "Tunisian", label: "Tunisian", code: "tn" },
  { value: "Turkish", label: "Turkish", code: "tr" },
  { value: "Turkmen", label: "Turkmen", code: "tm" },
  { value: "Turks and Caicos Island", label: "Turks and Caicos Island", code: "tc" },
  { value: "Tuvaluan", label: "Tuvaluan", code: "tv" },
  { value: "U.S. Virgin Island", label: "U.S. Virgin Island", code: "vi" },
  { value: "Ugandan", label: "Ugandan", code: "ug" },
  { value: "Ukrainian", label: "Ukrainian", code: "ua" },
  { value: "Uruguayan", label: "Uruguayan", code: "uy" },
  { value: "Uzbekistani, Uzbek", label: "Uzbekistani, Uzbek", code: "uz" },
  { value: "Vatican", label: "Vatican", code: "va" },
  { value: "Venezuelan", label: "Venezuelan", code: "ve" },
  { value: "Vietnamese", label: "Vietnamese", code: "vn" },
  { value: "Wallis and Futuna, Wallisian or Futunan", label: "Wallis and Futuna, Wallisian or Futunan", code: "wf" },
  { value: "Yemeni", label: "Yemeni", code: "ye" },
  { value: "Zambian", label: "Zambian", code: "zm" },
  { value: "Zimbabwean", label: "Zimbabwean", code: "zw" },
  { value: "Åland Island", label: "Åland Island", code: "ax" },
];
