# Generated by Django 4.2.30 on 2026-09-26 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matriculation_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("surname", models.CharField(max_length=150)),
                ("given_names", models.CharField(max_length=150)),
                ("date_of_birth", models.DateField()),
                ("place_of_birth", models.CharField(max_length=150)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("nationality", models.CharField(max_length=100)),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("identity_document_type", models.CharField(max_length=100)),
                ("identity_document_number", models.CharField(max_length=100)),
                ("identity_document_validity", models.DateField(blank=True, null=True)),
                (
                    "photograph",
                    models.ImageField(
                        blank=True, null=True, upload_to="employee_photos/"
                    ),
                ),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=50)),
                (
                    "personal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "professional_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("emergency_contact_name", models.CharField(max_length=150)),
                ("emergency_contact_number", models.CharField(max_length=50)),
                (
                    "social_insurance_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tax_identification_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "professional_identification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bank_key", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "method_of_payment",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("CASH", "Cash"),
                        ],
                        default="TRANSFER",
                        max_length=20,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent Contract"),
                            ("FIXED_TERM", "Fixed-Term Contract"),
                            ("INTERNSHIP", "Internship Agreement"),
                            ("TEMPORARY", "Temporary Work"),
                            ("APPRENTICESHIP", "Apprenticeship"),
                            ("SERVICE", "Service Contract"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_hire", models.DateField()),
                (
                    "classification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organisation.classification",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organisation.department",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organisation.position",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="organisation.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("date_of_birth", models.DateField()),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("SPOUSE", "Spouse"),
                            ("CHILD", "Child"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modification_date", models.DateTimeField(auto_now_add=True)),
                ("field_name", models.CharField(max_length=100)),
                ("previous_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ID", "Identity Document"),
                            ("DIPLOMA", "Diploma/Certificate"),
                            ("CONTRACT", "Contract"),
                            ("MEDICAL", "Medical Certificate"),
                            ("DISCIPLINARY", "Disciplinary Letter"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("file", models.FileField(upload_to="employee_documents/")),
                ("validity_date", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationAndExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("EDUCATION", "Education/Diploma"),
                            ("EXPERIENCE", "Professional Experience"),
                            ("LANGUAGE", "Language"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("institution_or_company", models.CharField(max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_experience",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
