# Generated by Django 4.2.30 on 2026-09-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_name_2",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_name_3",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_number_2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_number_3",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
