# Generated by Django 4.2.30 on 2026-09-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_emergency_contact_name_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_relationship_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_relationship_3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone_number_2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone_number_3",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
