# Generated by Django 4.2.30 on 2026-09-25 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_requires_password_change_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='A short description of the action performed.', max_length=255)),
                ('module', models.CharField(help_text="The system module where the action occurred (e.g., 'Auth', 'HR', 'Payroll').", max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='The IP address of the user.', null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional context or data regarding the action.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action. Null if anonymous or failed login.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
